spring:
  liquibase:
      change-log: classpath:db/changelog-master.xml

  kafka:
    template:
      default-topic: studenti
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092